version: '3.8'

services:
  wordle-tracker:
    image: ghcr.io/robert-mccausland/wordle-tracker:${VERSION}
    restart: unless-stopped 
    environment:
      DB_PATH: /var/lib/wordle-tracker/data/
      SYNC_COMMANDS: "TRUE"
      TOKEN: ${TOKEN}
      ENVIRONMENT: ${ENVIRONMENT}
      VERSION: ${VERSION}
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://grafana-alloy:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    volumes:
      - wordle-tracker-data:/var/lib/wordle-tracker/data

volumes:
  wordle-tracker-data:
    driver: local
